name: project_CI

on: push

jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses:  actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
    
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/testing'
    steps:
      - name: Connect to ssh host
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            echo 'Hello world!'
            cd ~/se2/19/se2-backend-group-19
            git reset --hard origin/testing
            git pull https://${{secrets.CLONE_TOKEN}}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-19 main
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-group-19'